a=int(input("Enter the number :"))
b=int(input("Enter the number :"))
print("Bitwise AND            :",a&b)
print("Bitwise OR             :",a|b)
print("Bitwise XOR            :",a^b)
print("Bitwise NOT            :",~a)
print("Bitwise NOT            :",~b)
print("Bitwise Left Shift     :",a<<b)
print("Bitwise Right Shift    :",a>>b)